### ISSUE TITLE
issue-1-subissue-1-homepage

### ISSUE THREAD

**Issue by jameswu49** [joseph-w-valdez/olive-garden-fanpage#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Creating Landing Page 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will log in and see a welcome page describing the site 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Splash Page (2)](https://github.com/joseph-w-valdez/olive-garden-fanpage/assets/117682160/9a3def99-d616-4e6d-871d-deb398bcc932)

![Splash Page (3)](https://github.com/joseph-w-valdez/olive-garden-fanpage/assets/117682160/a8421aa2-08ef-4b51-8478-2e2f10eb9b3d)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create navbar 
     - [x] hamburger icon 
     - [x] mobile links 
     - [x] sliding animation 
- [x] New font
- [x] New Icon or update icon 
- [x] Add new vines image 
- [x] Welcome message 
- [x] Add placeholder family image 
- [x] Create carousel system 
- [x] Create function to switch between tiles of any scroll amount 
- [x] Footer 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
