### ISSUE TITLE
issue-1-subissue-2-roulette

### ISSUE THREAD

**Issue by JordanTDawson** [joseph-w-valdez/olive-garden-fanpage#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click spin on button and roulette wheel will randomize a meal and choose for you.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Roulette Page (1)](https://github.com/joseph-w-valdez/olive-garden-fanpage/assets/117682160/3e47707b-098e-46bd-b12c-9f701866f9d2)

![Roulette Page - Clicked](https://github.com/joseph-w-valdez/olive-garden-fanpage/assets/117682160/38383872-feda-4c06-8889-4c79561dfb4c)

![Roulette Page (2)](https://github.com/joseph-w-valdez/olive-garden-fanpage/assets/117682160/0ca5265f-6355-45cb-a066-a41789df83f7)

![Roulette Page - Clicked (1)](https://github.com/joseph-w-valdez/olive-garden-fanpage/assets/117682160/bc542beb-e9e5-4025-81c5-62ff61eb5289)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Create an API for several Olive Garden items.
- [x] Create data structure for API with properties including name, price, type, image, alt, description.
- [x] Add in dummy data for several Olive Garden items.
- [x] Host API

### ☁️ Server Tasks

- [x] Create an endpoint for FETCHING the dummy data from the API.
- [x] Create function to grab 10 random items from the API and randomly choose one of them.
- [x] Return random item back to client side.

### ⚡ Client Tasks

- [x] Create spinner tile
- [x] Create spin button
- [x] Create function for spin button that
   - [x] accesses server endpoint 
   - [x] lifts the dish cover up
   - [x] disables button
   - [x] shows spinner component with menu items.
   - [x] shows selection perfectly aligned on dish.
- [x] Header tile with promotional text.
- [x] Selection tile with
   - [x] food image
   - [x] name of the item
   - [x] the price of the item
   - [x] description of the item
- [x] Create separate png files for the waiter and dish cover
- [x] Create function to move dish cover upwards
- [x] Create UI for spinner with 10 random items rotating through
- [x] Create function to update featured dish item to reflect the selected spinner item

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
